In [1]:
import numpy as np
import pandas as pd
from fyers_api import fyersModel
from datetime import datetime,timedelta

In [2]:
app_id="1dsjkla;ujg0"
app_secret="reyraurtywt46"
access_token="eyJ0eA"
fyers = fyersModel.FyersModel(client_id=app_id, token=access_token,log_path="/")

In [3]:
Dates = [ 
            
]

### Change the no of days back (max_limit:1875)

In [4]:
How_many_days_back=1875

In [5]:
IntervalLength=70

NoOfInvertal=int(How_many_days_back/IntervalLength)
print(NoOfInvertal)
for i in range(0,NoOfInvertal):
    new_date1=datetime.strftime(datetime.now()-timedelta(How_many_days_back-70*i),'%Y-%m-%d')
    Dates.append(new_date1)
    new_date2=datetime.strftime(datetime.now()-timedelta(How_many_days_back-70*(i+1)+1),'%Y-%m-%d')
    Dates.append(new_date2)
    if(i==NoOfInvertal-1):
        new_date1=datetime.strftime(datetime.now()-timedelta(How_many_days_back-70*(i+1)),'%Y-%m-%d')
        Dates.append(new_date1)
        
tomorrow_date=datetime.strftime(datetime.now()-timedelta(0),'%Y-%m-%d')
Dates.append(tomorrow_date)

26

In [6]:
Dates

['2017-05-18',
 '2017-07-26',
 '2017-07-27',
 '2017-10-04',
 '2017-10-05',
 '2017-12-13',
 '2017-12-14',
 '2018-02-21',
 '2018-02-22',
 '2018-05-02',
 '2018-05-03',
 '2018-07-11',
 '2018-07-12',
 '2018-09-19',
 '2018-09-20',
 '2018-11-28',
 '2018-11-29',
 '2019-02-06',
 '2019-02-07',
 '2019-04-17',
 '2019-04-18',
 '2019-06-26',
 '2019-06-27',
 '2019-09-04',
 '2019-09-05',
 '2019-11-13',
 '2019-11-14',
 '2020-01-22',
 '2020-01-23',
 '2020-04-01',
 '2020-04-02',
 '2020-06-10',
 '2020-06-11',
 '2020-08-19',
 '2020-08-20',
 '2020-10-28',
 '2020-10-29',
 '2021-01-06',
 '2021-01-07',
 '2021-03-17',
 '2021-03-18',
 '2021-05-26',
 '2021-05-27',
 '2021-08-04',
 '2021-08-05',
 '2021-10-13',
 '2021-10-14',
 '2021-12-22',
 '2021-12-23',
 '2022-03-02',
 '2022-03-03',
 '2022-05-11',
 '2022-05-12',
 '2022-07-06']

### Change the ticker you want to fetch data

In [7]:
ticker="NSE:NIFTYBANK-INDEX"

### Change the Resolution time 
#### Day : “D” or “1D”
#### 1 minute : “1”
#### 2 minute : “2"
#### 3 minute : "3"
#### 5 minute : "5"
#### 10 minute : "10"
#### 15 minute : "15"
#### 20 minute : "20"
#### 30 minute : "30"
#### 60 minute : "60"
#### 120 minute : "120"
#### 240 minute : "240"

In [8]:
Resolution="15"

In [9]:
column_names = ["date","time","open","high","low","close","volume"]
globalDataframe = pd.DataFrame(columns = column_names)
for i in range(0,len(Dates)-1,2):
    from_date=Dates[i]
    to_date=Dates[i+1]
    print(from_date)
    print(to_date)
    
    print(ticker)
    data = {"symbol":ticker,"resolution":Resolution,"date_format":"1","range_from":from_date,"range_to":to_date,"cont_flag":"1"}
    x=fyers.history(data)

    #print(x)
    y=x['candles']
    df=pd.DataFrame(y)
    df.columns=['date','open','high','low','close','volume']

    df['date'] = pd.to_datetime(df['date'],unit='s')
    df['date'] = df['date'].dt.tz_localize('utc').dt.tz_convert('Asia/Kolkata')
    df['date'] = df['date'].dt.tz_localize(None)
    df['time']=pd.to_datetime(df.date).dt.strftime('%H:%M')
    df['date']=pd.to_datetime(df.date).dt.strftime('%Y-%m-%d')
        
    print(df)
    globalDataframe=pd.concat([globalDataframe,df],ignore_index=True)

2017-05-18
2017-07-26
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
           date     open      high       low    close  volume   time
0    2017-07-17  24011.4  24011.40  24011.40  24011.4       0  09:00
1    2017-07-17  24011.4  24014.40  23954.05  23975.3       0  09:15
2    2017-07-17  23974.9  23984.85  23919.35  23920.9       0  09:30
3    2017-07-17  23919.8  23986.55  23914.40  23978.7       0  09:45
4    2017-07-17  23976.8  23982.45  23952.05  23968.1       0  10:00
..          ...      ...       ...       ...      ...     ...    ...
203  2017-07-26  24559.7  24592.60  24559.70  24584.8       0  14:15
204  2017-07-26  24587.2  24596.80  24577.80  24596.8       0  14:30
205  2017-07-26  24604.0  24635.20  24604.00  24634.3       0  14:45
206  2017-07-26  24630.5  24711.30  24630.50  24698.6       0  15:00
207  2017-07-26  24710.2  24710.20  24676.45  24680.1       0  15:15

[208 rows x 7 columns]
2017-07-27
2017-10-04
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2017-07-27  24857.5  24857.50  24857.50  24857.5       0  09:00
1     2017-07-27  24828.8  24888.75  24828.75  24878.2       0  09:15
2     2017-07-27  24877.5  24885.90  24871.95  24880.3       0  09:30
3     2017-07-27  24874.2  24906.80  24864.55  24905.2       0  09:45
4     2017-07-27  24904.0  24904.00  24879.85  24889.0       0  10:00
...          ...      ...       ...       ...      ...     ...    ...
1216  2017-10-04  24126.8  24149.70  24093.85  24120.1       0  14:15
1217  2017-10-04  24125.8  24215.50  24059.85  24208.6       0  14:30
1218  2017-10-04  24207.9  24228.60  24165.50  24199.4       0  14:45
1219  2017-10-04  24199.8  24203.30  24071.35  24104.7       0  15:00
1220  2017-10-04  24105.3  24112.80  24078.95  24098.4       0  15:15

[1221 rows x 7 columns]
2017-10-05
2017-12-13
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2017-10-05  24114.8  24114.75  24114.75  24114.8       0  09:00
1     2017-10-05  24114.8  24154.35  24076.45  24151.1       0  09:15
2     2017-10-05  24153.3  24166.55  24129.55  24153.8       0  09:30
3     2017-10-05  24152.3  24166.35  24144.25  24161.8       0  09:45
4     2017-10-05  24163.3  24188.10  24153.45  24166.2       0  10:00
...          ...      ...       ...       ...      ...     ...    ...
1245  2017-12-13  24947.4  25029.20  24939.65  25028.7       0  14:15
1246  2017-12-13  25027.2  25033.00  24990.65  24993.9       0  14:30
1247  2017-12-13  24994.1  25003.10  24952.55  24968.1       0  14:45
1248  2017-12-13  24969.1  25014.05  24954.25  25005.3       0  15:00
1249  2017-12-13  25007.7  25039.15  25006.20  25029.9       0  15:15

[1250 rows x 7 columns]
2017-12-14
2018-02-21
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2017-12-14  25062.4  25069.20  24966.25  25028.8       0  09:15
1     2017-12-14  25028.8  25042.80  24959.75  24963.9       0  09:30
2     2017-12-14  24962.8  25005.25  24944.35  25002.2       0  09:45
3     2017-12-14  25002.2  25031.20  25000.65  25010.3       0  10:00
4     2017-12-14  25010.4  25035.85  24992.10  25007.8       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1166  2018-02-21  24933.9  24960.95  24890.00  24911.6       0  14:15
1167  2018-02-21  24910.7  24953.25  24890.20  24893.7       0  14:30
1168  2018-02-21  24897.8  24947.80  24887.15  24916.7       0  14:45
1169  2018-02-21  24914.9  24971.95  24905.95  24931.1       0  15:00
1170  2018-02-21  24932.8  24953.10  24909.05  24924.4       0  15:15

[1171 rows x 7 columns]
2018-02-22
2018-05-02
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2018-02-22  24812.7  24865.50  24796.60  24863.7       0  09:15
1     2018-02-22  24863.1  24880.45  24820.45  24849.1       0  09:30
2     2018-02-22  24850.3  24890.55  24840.60  24862.2       0  09:45
3     2018-02-22  24862.0  24877.10  24847.35  24862.8       0  10:00
4     2018-02-22  24861.8  24877.70  24850.20  24861.9       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1148  2018-05-02  25580.2  25595.45  25542.00  25546.7       0  14:15
1149  2018-05-02  25548.3  25602.25  25540.15  25553.6       0  14:30
1150  2018-05-02  25556.3  25560.30  25499.35  25545.9       0  14:45
1151  2018-05-02  25546.5  25587.00  25530.30  25582.8       0  15:00
1152  2018-05-02  25583.6  25596.20  25565.25  25579.2       0  15:15

[1153 rows x 7 columns]
2018-05-03
2018-07-11
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2018-05-03  25547.9  25559.70  25469.05  25512.6       0  09:15
1     2018-05-03  25514.8  25547.60  25480.55  25514.2       0  09:30
2     2018-05-03  25514.6  25584.55  25508.55  25550.0       0  09:45
3     2018-05-03  25548.4  25578.80  25521.65  25525.9       0  10:00
4     2018-05-03  25524.9  25545.20  25508.85  25541.0       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1245  2018-07-11  26800.1  26858.10  26796.60  26842.9       0  14:15
1246  2018-07-11  26842.3  26852.75  26793.30  26793.9       0  14:30
1247  2018-07-11  26794.8  26826.45  26791.85  26809.3       0  14:45
1248  2018-07-11  26809.2  26821.25  26792.90  26813.1       0  15:00
1249  2018-07-11  26812.1  26839.25  26798.50  26814.5       0  15:15

[1250 rows x 7 columns]
2018-07-12
2018-09-19
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2018-07-12  26937.5  27073.00  26936.05  27060.7       0  09:15
1     2018-07-12  27061.3  27076.25  27042.15  27063.1       0  09:30
2     2018-07-12  27063.7  27100.25  27061.25  27092.6       0  09:45
3     2018-07-12  27092.8  27137.30  27091.95  27131.8       0  10:00
4     2018-07-12  27135.8  27164.65  27117.45  27130.9       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1170  2018-09-19  26369.7  26384.25  26339.55  26347.1       0  14:15
1171  2018-09-19  26346.0  26346.70  26251.25  26277.9       0  14:30
1172  2018-09-19  26278.7  26325.30  26235.70  26318.7       0  14:45
1173  2018-09-19  26317.6  26348.10  26244.65  26273.2       0  15:00
1174  2018-09-19  26272.8  26307.50  26266.95  26285.7       0  15:15

[1175 rows x 7 columns]
2018-09-20
2018-11-28
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2018-09-21  26331.1  26490.40  26251.20  26426.3       0  09:15
1     2018-09-21  26426.3  26471.90  26402.20  26470.6       0  09:30
2     2018-09-21  26469.9  26488.75  26439.75  26454.7       0  09:45
3     2018-09-21  26454.4  26479.30  26438.65  26441.7       0  10:00
4     2018-09-21  26441.8  26459.00  26332.65  26373.9       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1099  2018-11-28  26448.4  26487.55  26419.65  26482.8       0  14:15
1100  2018-11-28  26481.5  26549.30  26480.25  26535.5       0  14:30
1101  2018-11-28  26537.0  26546.95  26476.30  26489.3       0  14:45
1102  2018-11-28  26486.9  26500.60  26454.65  26462.9       0  15:00
1103  2018-11-28  26461.2  26473.00  26428.90  26446.4       0  15:15

[1104 rows x 7 columns]
2018-11-29
2019-02-06
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2018-11-29  26641.6  26650.55  26577.15  26594.1       0  09:15
1     2018-11-29  26594.3  26627.80  26593.70  26614.5       0  09:30
2     2018-11-29  26613.5  26629.30  26601.50  26612.4       0  09:45
3     2018-11-29  26611.8  26631.00  26598.75  26614.8       0  10:00
4     2018-11-29  26614.7  26637.95  26608.65  26628.8       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1220  2019-02-06  27376.1  27383.15  27331.60  27352.7       0  14:15
1221  2019-02-06  27352.3  27393.05  27340.75  27385.9       0  14:30
1222  2019-02-06  27387.3  27411.50  27363.45  27403.2       0  14:45
1223  2019-02-06  27403.2  27414.30  27377.60  27398.0       0  15:00
1224  2019-02-06  27396.8  27428.65  27377.70  27405.7       0  15:15

[1225 rows x 7 columns]
2019-02-07
2019-04-17
NSE:NIFTYBANK-INDEX

ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2019-02-07  27424.1  27469.25  27380.35  27461.1       0  09:15
1     2019-02-07  27460.6  27481.10  27427.65  27434.8       0  09:30
2     2019-02-07  27435.3  27435.30  27354.30  27395.3       0  09:45
3     2019-02-07  27396.1  27434.05  27394.25  27427.4       0  10:00
4     2019-02-07  27427.4  27476.35  27426.65  27470.3       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1170  2019-04-16  30538.9  30551.15  30495.75  30525.2       0  14:15
1171  2019-04-16  30525.0  30590.95  30520.95  30559.2       0  14:30
1172  2019-04-16  30556.8  30560.30  30513.90  30523.1       0  14:45
1173  2019-04-16  30523.0  30527.95  30480.10  30506.7       0  15:00
1174  2019-04-16  30508.4  30575.45  30502.50  30564.1       0  15:15

[1175 rows x 7 columns]
2019-04-18
2019-06-26
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2019-04-18  30656.5  30669.80  30566.10  30579.1       0  09:15
1     2019-04-18  30581.7  30591.05  30445.10  30453.6       0  09:30
2     2019-04-18  30453.3  30481.20  30397.15  30414.2       0  09:45
3     2019-04-18  30415.4  30439.95  30357.45  30378.0       0  10:00
4     2019-04-18  30377.8  30382.80  30314.75  30357.3       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1145  2019-06-26  31076.8  31096.35  31051.50  31076.8       0  14:15
1146  2019-06-26  31078.7  31156.15  31045.00  31148.7       0  14:30
1147  2019-06-26  31147.3  31202.70  31137.90  31184.8       0  14:45
1148  2019-06-26  31187.4  31189.55  31140.50  31176.3       0  15:00
1149  2019-06-26  31175.3  31177.40  31127.65  31127.7       0  15:15

[1150 rows x 7 columns]
2019-06-27
2019-09-04
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2019-06-27  31192.1  31300.35  31167.10  31278.6       0  09:15
1     2019-06-27  31278.5  31285.65  31244.50  31247.7       0  09:30
2     2019-06-27  31250.0  31283.25  31241.00  31254.4       0  09:45
3     2019-06-27  31256.0  31339.05  31253.80  31319.2       0  10:00
4     2019-06-27  31318.8  31363.70  31310.35  31349.3       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1170  2019-09-04  27195.2  27202.30  27019.30  27048.6       0  14:15
1171  2019-09-04  27038.5  27141.65  27035.10  27138.2       0  14:30
1172  2019-09-04  27136.8  27162.45  27090.15  27108.1       0  14:45
1173  2019-09-04  27106.7  27186.55  27106.65  27143.2       0  15:00
1174  2019-09-04  27144.0  27145.15  27071.05  27096.2       0  15:15

[1175 rows x 7 columns]
2019-09-05
2019-11-13
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2019-09-05  27086.9  27243.95  27055.35  27141.3       0  09:15
1     2019-09-05  27137.2  27147.00  27014.60  27025.8       0  09:30
2     2019-09-05  27030.0  27109.20  26996.15  27082.3       0  09:45
3     2019-09-05  27085.0  27150.95  27083.55  27144.9       0  10:00
4     2019-09-05  27142.8  27173.80  27083.20  27168.9       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1107  2019-11-13  30820.2  30832.60  30755.55  30775.8       0  14:15
1108  2019-11-13  30772.1  30789.50  30690.15  30698.6       0  14:30
1109  2019-11-13  30699.8  30713.70  30539.30  30556.0       0  14:45
1110  2019-11-13  30559.1  30608.90  30488.10  30517.1       0  15:00
1111  2019-11-13  30523.3  30570.85  30501.05  30544.4       0  15:15

[1112 rows x 7 columns]
2019-11-14
2020-01-22
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2019-11-14  30615.8  30623.75  30426.80  30457.0       0  09:15
1     2019-11-14  30459.2  30481.40  30338.35  30356.2       0  09:30
2     2019-11-14  30353.6  30440.05  30353.20  30385.7       0  09:45
3     2019-11-14  30383.2  30487.95  30382.90  30443.7       0  10:00
4     2019-11-14  30440.4  30457.15  30419.95  30450.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1220  2020-01-22  30660.2  30682.60  30619.70  30648.2       0  14:15
1221  2020-01-22  30648.1  30692.25  30645.35  30664.8       0  14:30
1222  2020-01-22  30664.8  30726.85  30651.25  30691.8       0  14:45
1223  2020-01-22  30691.2  30741.50  30690.65  30705.2       0  15:00
1224  2020-01-22  30704.7  30716.05  30675.10  30691.8       0  15:15

[1225 rows x 7 columns]
2020-01-23
2020-04-01
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2020-01-23  30742.2  30893.45  30621.35  30875.2       0  09:15
1     2020-01-23  30873.6  30954.10  30868.05  30887.0       0  09:30
2     2020-01-23  30883.3  30906.80  30845.10  30879.0       0  09:45
3     2020-01-23  30876.1  30884.20  30857.55  30862.6       0  10:00
4     2020-01-23  30862.5  30879.05  30800.95  30821.6       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1214  2020-04-01  18124.8  18198.30  18106.80  18129.9       0  14:15
1215  2020-04-01  18126.1  18165.70  18092.55  18139.1       0  14:30
1216  2020-04-01  18139.4  18257.80  18097.25  18235.2       0  14:45
1217  2020-04-01  18236.1  18290.50  18181.65  18203.7       0  15:00
1218  2020-04-01  18206.8  18229.45  18174.75  18207.3       0  15:15

[1219 rows x 7 columns]
2020-04-02
2020-06-10
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2020-04-03  18325.1  18326.10  17515.90  17626.0       0  09:15
1     2020-04-03  17627.2  17715.75  17591.90  17685.1       0  09:30
2     2020-04-03  17687.9  17921.25  17687.25  17769.2       0  09:45
3     2020-04-03  17765.6  17858.45  17710.75  17827.1       0  10:00
4     2020-04-03  17826.2  17864.55  17722.25  17749.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1095  2020-06-10  20935.1  20977.15  20879.35  20902.2       0  14:15
1096  2020-06-10  20900.9  20900.90  20733.60  20772.8       0  14:30
1097  2020-06-10  20778.1  20855.75  20744.80  20814.3       0  14:45
1098  2020-06-10  20809.2  21170.35  20800.05  21169.2       0  15:00
1099  2020-06-10  21167.1  21251.45  21152.75  21240.2       0  15:15

[1100 rows x 7 columns]
2020-06-11
2020-08-19
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2020-06-11  21084.7  21107.55  20900.10  21008.1       0  09:15
1     2020-06-11  21008.7  21244.45  20991.90  21163.2       0  09:30
2     2020-06-11  21164.2  21189.30  21102.95  21135.9       0  09:45
3     2020-06-11  21137.0  21215.00  21132.35  21163.4       0  10:00
4     2020-06-11  21162.6  21172.65  21118.60  21159.2       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1245  2020-08-19  22372.4  22390.95  22297.25  22338.9       0  14:15
1246  2020-08-19  22338.0  22358.95  22272.25  22289.8       0  14:30
1247  2020-08-19  22289.8  22354.45  22289.85  22339.6       0  14:45
1248  2020-08-19  22341.8  22341.80  22236.00  22270.1       0  15:00
1249  2020-08-19  22274.8  22313.10  22264.55  22295.7       0  15:15

[1250 rows x 7 columns]
2020-08-20
2020-10-28
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2020-08-20  21989.9  22025.85  21931.85  21984.2       0  09:15
1     2020-08-20  21984.9  22053.35  21953.95  22044.4       0  09:30
2     2020-08-20  22043.2  22059.55  22017.80  22040.2       0  09:45
3     2020-08-20  22040.8  22041.90  21996.15  21997.4       0  10:00
4     2020-08-20  21997.1  22018.05  21983.70  21992.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1220  2020-10-28  24180.9  24261.10  24128.30  24241.7       0  14:15
1221  2020-10-28  24244.9  24251.45  24133.15  24225.6       0  14:30
1222  2020-10-28  24225.2  24263.95  24174.00  24218.2       0  14:45
1223  2020-10-28  24220.1  24252.80  24176.95  24211.9       0  15:00
1224  2020-10-28  24213.6  24296.05  24205.65  24277.4       0  15:15

[1225 rows x 7 columns]
2020-10-29
2021-01-06
NSE:NIFTYBANK-INDEX

ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2020-10-29  24063.5  24104.85  23923.85  24044.1       0  09:15
1     2020-10-29  24043.3  24181.75  24015.15  24146.7       0  09:30
2     2020-10-29  24139.2  24218.25  24110.35  24173.2       0  09:45
3     2020-10-29  24175.6  24218.90  24105.55  24183.2       0  10:00
4     2020-10-29  24181.9  24194.65  24041.00  24061.8       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1174  2021-01-06  31635.2  31777.35  31601.20  31711.4       0  14:15
1175  2021-01-06  31711.1  31806.85  31638.40  31806.1       0  14:30
1176  2021-01-06  31808.0  31859.80  31786.70  31839.2       0  14:45
1177  2021-01-06  31839.2  31865.60  31775.40  31808.2       0  15:00
1178  2021-01-06  31806.3  31839.10  31711.50  31739.4       0  15:15

[1179 rows x 7 columns]
2021-01-07
2021-03-17
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-01-07  32129.8  32142.90  32003.70  32114.6       0  09:15
1     2021-01-07  32113.4  32147.80  32049.70  32057.5       0  09:30
2     2021-01-07  32055.8  32073.75  32009.65  32032.6       0  09:45
3     2021-01-07  32033.3  32056.40  31965.10  31995.8       0  10:00
4     2021-01-07  31994.3  32045.55  31954.95  31982.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1181  2021-03-17  34521.2  34548.00  34435.30  34487.4       0  14:15
1182  2021-03-17  34486.6  34534.30  34439.05  34486.0       0  14:30
1183  2021-03-17  34486.8  34542.55  34464.20  34508.4       0  14:45
1184  2021-03-17  34505.9  34531.45  34148.65  34168.1       0  15:00
1185  2021-03-17  34166.3  34222.15  34131.50  34140.9       0  15:15

[1186 rows x 7 columns]
2021-03-18
2021-05-26
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-03-18  34577.5  34736.90  34504.15  34614.8       0  09:15
1     2021-03-18  34613.3  34715.55  34585.30  34714.8       0  09:30
2     2021-03-18  34715.1  34759.85  34664.55  34690.6       0  09:45
3     2021-03-18  34686.9  34708.65  34574.75  34592.5       0  10:00
4     2021-03-18  34599.8  34635.60  34548.00  34593.4       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1120  2021-05-26  34765.2  34825.65  34733.70  34761.6       0  14:15
1121  2021-05-26  34761.1  34826.10  34753.60  34801.7       0  14:30
1122  2021-05-26  34800.4  34804.00  34741.00  34745.4       0  14:45
1123  2021-05-26  34741.0  34750.20  34634.40  34688.7       0  15:00
1124  2021-05-26  34686.8  34708.00  34651.70  34674.7       0  15:15

[1125 rows x 7 columns]
2021-05-27
2021-08-04
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-05-27  34664.2  34756.60  34565.90  34577.9       0  09:15
1     2021-05-27  34576.9  34612.90  34537.30  34558.1       0  09:30
2     2021-05-27  34558.2  34600.20  34533.75  34586.9       0  09:45
3     2021-05-27  34585.6  34666.25  34585.45  34616.1       0  10:00
4     2021-05-27  34615.8  34654.65  34604.70  34615.6       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1220  2021-08-04  36139.2  36219.80  36134.20  36188.6       0  14:15
1221  2021-08-04  36191.2  36209.55  36025.15  36061.9       0  14:30
1222  2021-08-04  36055.1  36109.60  36034.05  36080.4       0  14:45
1223  2021-08-04  36079.4  36098.40  36042.80  36062.1       0  15:00
1224  2021-08-04  36060.2  36061.15  35950.70  35994.5       0  15:15

[1225 rows x 7 columns]
2021-08-05
2021-10-13
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-08-05  36093.9  36008.75  35816.30  35772.8       0  09:15
1     2021-08-05  35769.9  35915.00  35747.45  35892.0       0  09:30
2     2021-08-05  35891.9  35952.60  35867.40  35859.5       0  09:45
3     2021-08-05  35857.9  35836.40  35765.55  35779.2       0  10:00
4     2021-08-05  35781.6  35836.45  35719.20  35739.8       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1195  2021-10-13  38665.7  38757.15  38665.70  38707.8       0  14:15
1196  2021-10-13  38708.0  38717.45  38655.40  38670.4       0  14:30
1197  2021-10-13  38668.1  38691.15  38606.30  38690.9       0  14:45
1198  2021-10-13  38686.4  38694.50  38622.90  38637.2       0  15:00
1199  2021-10-13  38637.8  38647.55  38575.35  38584.2       0  15:15

[1200 rows x 7 columns]
2021-10-14
2021-12-22
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-10-14  38684.6  38782.70  38673.00  38782.7       0  09:15
1     2021-10-14  38777.9  38879.75  38777.85  38856.2       0  09:30
2     2021-10-14  38854.8  38869.60  38833.95  38856.2       0  09:45
3     2021-10-14  38856.3  38897.80  38810.40  38851.8       0  10:00
4     2021-10-14  38844.8  38858.40  38813.85  38845.8       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1152  2021-12-22  34805.2  34903.85  34780.75  34900.7       0  14:15
1153  2021-12-22  34903.2  34921.60  34824.80  34862.6       0  14:30
1154  2021-12-22  34866.1  34998.50  34863.60  34987.6       0  14:45
1155  2021-12-22  34986.6  35051.25  34984.00  34997.4       0  15:00
1156  2021-12-22  35002.3  35112.10  34987.90  35095.2       0  15:15

[1157 rows x 7 columns]
2021-12-23
2022-03-02
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2021-12-23  35350.5  35359.40  35186.15  35196.2       0  09:15
1     2021-12-23  35191.1  35231.80  35149.00  35201.8       0  09:30
2     2021-12-23  35202.1  35268.30  35168.95  35168.9       0  09:45
3     2021-12-23  35170.8  35202.10  35126.85  35135.9       0  10:00
4     2021-12-23  35136.5  35158.20  35093.20  35134.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1195  2022-03-02  35044.2  35056.15  34914.50  34942.8       0  14:15
1196  2022-03-02  34941.2  35065.30  34902.90  35057.5       0  14:30
1197  2022-03-02  35056.1  35082.05  34995.05  35027.4       0  14:45
1198  2022-03-02  35029.1  35403.45  35029.15  35394.8       0  15:00
1199  2022-03-02  35392.4  35545.95  35392.35  35475.8       0  15:15

[1200 rows x 7 columns]
2022-03-03
2022-05-11
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
            date     open      high       low    close  volume   time
0     2022-03-03  35621.1  35804.15  35518.20  35524.9       0  09:15
1     2022-03-03  35521.9  35536.20  35317.70  35320.1       0  09:30
2     2022-03-03  35317.2  35365.60  35248.55  35325.7       0  09:45
3     2022-03-03  35323.5  35328.80  35199.65  35267.1       0  10:00
4     2022-03-03  35267.1  35290.20  35148.95  35172.1       0  10:15
...          ...      ...       ...       ...      ...     ...    ...
1143  2022-05-11  34640.5  34665.40  34601.30  34654.1       0  14:15
1144  2022-05-11  34656.2  34722.35  34514.70  34720.0       0  14:30
1145  2022-05-11  34720.2  34738.35  34639.35  34700.7       0  14:45
1146  2022-05-11  34696.9  34712.05  34575.35  34683.5       0  15:00
1147  2022-05-11  34683.9  34793.20  34669.85  34776.2       0  15:15

[1148 rows x 7 columns]
2022-05-12
2022-07-06
NSE:NIFTYBANK-INDEX
ERR: logEntryFunc: history : [Errno 2] No such file or directory: '//2022-07-06.txt'
           date      open      high       low     close  volume   time
0    2022-05-12  34289.10  34341.20  34018.75  34027.80       0  09:15
1    2022-05-12  34038.40  34089.40  33837.65  33887.80       0  09:30
2    2022-05-12  33888.40  33961.85  33865.70  33947.10       0  09:45
3    2022-05-12  33951.60  33985.25  33854.05  33884.60       0  10:00
4    2022-05-12  33879.90  33988.50  33832.10  33971.70       0  10:15
..          ...       ...       ...       ...       ...     ...    ...
995  2022-07-06  34217.25  34348.20  34196.85  34285.05       0  14:15
996  2022-07-06  34283.85  34283.85  34152.50  34168.00       0  14:30
997  2022-07-06  34167.40  34312.05  34150.75  34309.00       0  14:45
998  2022-07-06  34310.85  34333.50  34254.60  34331.45       0  15:00
999  2022-07-06  34323.50  34382.75  34322.65  34355.55       0  15:15

[1000 rows x 7 columns]

In [10]:
globalDataframe

             date   time      open      high       low     close volume
0      2017-07-17  09:00   24011.4   24011.4   24011.4   24011.4      0
1      2017-07-17  09:15   24011.4   24014.4  23954.05   23975.3      0
2      2017-07-17  09:30   23974.9  23984.85  23919.35   23920.9      0
3      2017-07-17  09:45   23919.8  23986.55   23914.4   23978.7      0
4      2017-07-17  10:00   23976.8  23982.45  23952.05   23968.1      0
...           ...    ...       ...       ...       ...       ...    ...
30803  2022-07-06  14:15  34217.25   34348.2  34196.85  34285.05      0
30804  2022-07-06  14:30  34283.85  34283.85   34152.5   34168.0      0
30805  2022-07-06  14:45   34167.4  34312.05  34150.75   34309.0      0
30806  2022-07-06  15:00  34310.85   34333.5   34254.6  34331.45      0
30807  2022-07-06  15:15   34323.5  34382.75  34322.65  34355.55      0

[30808 rows x 7 columns]

In [11]:
globalDataframe = globalDataframe.astype({'open':'float64','high':'float64','low':'float64','close':'float64','volume':'int64'})

In [12]:
globalDataframe.to_csv(f"C:\\Users\\Lenovo\\Desktop\\FyersData\\{ticker[4:]}_{Resolution}min_{Dates[0]}_to_{Dates[-1]}.csv")